apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dot171628449 
  janus-idp.io/tekton: dot171628449
  backstage.io/kubernetes-id: dot171628449
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dot171628449
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  